// Code generated by ent, DO NOT EDIT.

package paymentchannel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldGroupID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldPlatform, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldRateMultiplier, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldDescription, v))
}

// Models applies equality check predicate on the "models" field. It's identical to ModelsEQ.
func Models(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldModels, v))
}

// Features applies equality check predicate on the "features" field. It's identical to FeaturesEQ.
func Features(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldFeatures, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldSortOrder, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotNull(FieldGroupID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContainsFold(FieldPlatform, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v decimal.Decimal) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldRateMultiplier, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContainsFold(FieldDescription, v))
}

// ModelsEQ applies the EQ predicate on the "models" field.
func ModelsEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldModels, v))
}

// ModelsNEQ applies the NEQ predicate on the "models" field.
func ModelsNEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldModels, v))
}

// ModelsIn applies the In predicate on the "models" field.
func ModelsIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldModels, vs...))
}

// ModelsNotIn applies the NotIn predicate on the "models" field.
func ModelsNotIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldModels, vs...))
}

// ModelsGT applies the GT predicate on the "models" field.
func ModelsGT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldModels, v))
}

// ModelsGTE applies the GTE predicate on the "models" field.
func ModelsGTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldModels, v))
}

// ModelsLT applies the LT predicate on the "models" field.
func ModelsLT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldModels, v))
}

// ModelsLTE applies the LTE predicate on the "models" field.
func ModelsLTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldModels, v))
}

// ModelsContains applies the Contains predicate on the "models" field.
func ModelsContains(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContains(FieldModels, v))
}

// ModelsHasPrefix applies the HasPrefix predicate on the "models" field.
func ModelsHasPrefix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasPrefix(FieldModels, v))
}

// ModelsHasSuffix applies the HasSuffix predicate on the "models" field.
func ModelsHasSuffix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasSuffix(FieldModels, v))
}

// ModelsIsNil applies the IsNil predicate on the "models" field.
func ModelsIsNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIsNull(FieldModels))
}

// ModelsNotNil applies the NotNil predicate on the "models" field.
func ModelsNotNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotNull(FieldModels))
}

// ModelsEqualFold applies the EqualFold predicate on the "models" field.
func ModelsEqualFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEqualFold(FieldModels, v))
}

// ModelsContainsFold applies the ContainsFold predicate on the "models" field.
func ModelsContainsFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContainsFold(FieldModels, v))
}

// FeaturesEQ applies the EQ predicate on the "features" field.
func FeaturesEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldFeatures, v))
}

// FeaturesNEQ applies the NEQ predicate on the "features" field.
func FeaturesNEQ(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldFeatures, v))
}

// FeaturesIn applies the In predicate on the "features" field.
func FeaturesIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldFeatures, vs...))
}

// FeaturesNotIn applies the NotIn predicate on the "features" field.
func FeaturesNotIn(vs ...string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldFeatures, vs...))
}

// FeaturesGT applies the GT predicate on the "features" field.
func FeaturesGT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldFeatures, v))
}

// FeaturesGTE applies the GTE predicate on the "features" field.
func FeaturesGTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldFeatures, v))
}

// FeaturesLT applies the LT predicate on the "features" field.
func FeaturesLT(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldFeatures, v))
}

// FeaturesLTE applies the LTE predicate on the "features" field.
func FeaturesLTE(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldFeatures, v))
}

// FeaturesContains applies the Contains predicate on the "features" field.
func FeaturesContains(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContains(FieldFeatures, v))
}

// FeaturesHasPrefix applies the HasPrefix predicate on the "features" field.
func FeaturesHasPrefix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasPrefix(FieldFeatures, v))
}

// FeaturesHasSuffix applies the HasSuffix predicate on the "features" field.
func FeaturesHasSuffix(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldHasSuffix(FieldFeatures, v))
}

// FeaturesIsNil applies the IsNil predicate on the "features" field.
func FeaturesIsNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIsNull(FieldFeatures))
}

// FeaturesNotNil applies the NotNil predicate on the "features" field.
func FeaturesNotNil() predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotNull(FieldFeatures))
}

// FeaturesEqualFold applies the EqualFold predicate on the "features" field.
func FeaturesEqualFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEqualFold(FieldFeatures, v))
}

// FeaturesContainsFold applies the ContainsFold predicate on the "features" field.
func FeaturesContainsFold(v string) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldContainsFold(FieldFeatures, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldLTE(FieldSortOrder, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.FieldNEQ(FieldEnabled, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.PaymentChannel {
	return predicate.PaymentChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.PaymentChannel {
	return predicate.PaymentChannel(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentChannel) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentChannel) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentChannel) predicate.PaymentChannel {
	return predicate.PaymentChannel(sql.NotPredicates(p))
}
